# Generated by Django 2.0.5 on 2018-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=100),
        ),
    ]
